// <auto-generated />
using System;
using CivicSync.EntityFrameworkCore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace CivicSync.EntityFrameworkCore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CivicSyncDbContext))]
    [Migration("20260604070924_AddCitizenRecordVersioning")]
    partial class AddCitizenRecordVersioning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CivicSync.Web.Host.Domain.ChangeRequests.ChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CommittedCitizenVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExpectedCitizenVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RequestedAtNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChangeRequests", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.ChangeRequests.DepartmentApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApproverDepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApproverFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovingNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId", "ApprovingNodeId")
                        .IsUnique();

                    b.ToTable("DepartmentApprovals", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.ChangeRequests.FieldChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId");

                    b.ToTable("FieldChanges", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Citizens.Citizen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NationalIdNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("RecordVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentNodeId", "NationalIdNumber")
                        .IsUnique();

                    b.ToTable("Citizens", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Citizens.CitizenReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LastLedgerSequenceApplied")
                        .HasColumnType("bigint");

                    b.Property<string>("SharedDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentNodeId", "CitizenId")
                        .IsUnique();

                    b.ToTable("CitizenReplicas", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Ledger.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OriginatingNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OriginatingNodeId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("LedgerEntries", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Nodes.DepartmentNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.ToTable("DepartmentNodes", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Nodes.DepartmentUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentNodeId", "EmailAddress")
                        .IsUnique();

                    b.ToTable("DepartmentUsers", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Nodes.KnownPeerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LastSyncedSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("PeerBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PeerDepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentNodeId", "PeerDepartmentCode")
                        .IsUnique();

                    b.ToTable("KnownPeerNodes", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Sync.NodeSyncReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SyncOutboxEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SyncOutboxEventId", "TargetNodeId")
                        .IsUnique();

                    b.ToTable("NodeSyncReceipts", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Sync.SyncInboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CitizenNationalIdNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldChangesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceivedFromNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentNodeId", "LedgerEntryId")
                        .IsUnique();

                    b.ToTable("SyncInboxEntries", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Sync.SyncOutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentNodeId", "LedgerEntryId")
                        .IsUnique();

                    b.ToTable("SyncOutboxEvents", (string)null);
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.ChangeRequests.DepartmentApproval", b =>
                {
                    b.HasOne("CivicSync.Web.Host.Domain.ChangeRequests.ChangeRequest", null)
                        .WithMany("Approvals")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.ChangeRequests.FieldChange", b =>
                {
                    b.HasOne("CivicSync.Web.Host.Domain.ChangeRequests.ChangeRequest", null)
                        .WithMany("FieldChanges")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Citizens.Citizen", b =>
                {
                    b.OwnsOne("CivicSync.Web.Host.Domain.ValueObjects.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("EmailAddress");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("CitizenId");

                            b1.ToTable("Citizens");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.OwnsOne("CivicSync.Web.Host.Domain.ValueObjects.PersonName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("CitizenId");

                            b1.ToTable("Citizens");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.Navigation("ContactDetails")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Ledger.LedgerEntry", b =>
                {
                    b.OwnsOne("CivicSync.Web.Host.Domain.ValueObjects.RecordProof", "CurrentProof", b1 =>
                        {
                            b1.Property<Guid>("LedgerEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("CurrentProofHash");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("LedgerEntries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.OwnsOne("CivicSync.Web.Host.Domain.ValueObjects.RecordProof", "PayloadProof", b1 =>
                        {
                            b1.Property<Guid>("LedgerEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("PayloadProofHash");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("LedgerEntries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.OwnsOne("CivicSync.Web.Host.Domain.ValueObjects.RecordProof", "PreviousProof", b1 =>
                        {
                            b1.Property<Guid>("LedgerEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("PreviousProofHash");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("LedgerEntries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.Navigation("CurrentProof")
                        .IsRequired();

                    b.Navigation("PayloadProof")
                        .IsRequired();

                    b.Navigation("PreviousProof")
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Nodes.DepartmentUser", b =>
                {
                    b.HasOne("CivicSync.Web.Host.Domain.Nodes.DepartmentNode", null)
                        .WithMany()
                        .HasForeignKey("DepartmentNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Nodes.KnownPeerNode", b =>
                {
                    b.HasOne("CivicSync.Web.Host.Domain.Nodes.DepartmentNode", null)
                        .WithMany("KnownPeers")
                        .HasForeignKey("DepartmentNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.ChangeRequests.ChangeRequest", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("FieldChanges");
                });

            modelBuilder.Entity("CivicSync.Web.Host.Domain.Nodes.DepartmentNode", b =>
                {
                    b.Navigation("KnownPeers");
                });
#pragma warning restore 612, 618
        }
    }
}
